server:
  port: 7002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter
      routes[0]:
        id: customer-service
        predicates[0]: Path=/customer-service/api/v1/customers/**
        predicates[1]: Path=/customer-service/api/v1/addresses/**
        predicates[2]: Path=/customer-service/api/v1/cities/**
        predicates[3]: Path=/customer-service/api/v1/individual-customers/**
        uri: lb://customerService
      routes[1]:
        id: discovery-server
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
        uri: http://localhost:7000
      routes[2]:
        id: identity-service
        predicates[0]: Path=/identity-service/api/v1/auth/**
        uri: lb://identityService
      routes[3]:
        id: search-service
        predicates[0]: Path=/search-service/api/v1/customers/**
        uri: lb://searchService
      routes[4]:
        id: account-service
        predicates[0]: Path=/account-service/api/v1/accounts/**
        uri: lb://accountService
